name: ClarityVault2026 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # --- Job 1: Frontend Application Build & Test ---
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Consistent Node.js version
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Check code format
        run: npm run format

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: build/

  # --- Job 2: Smart Contracts Test ---
  test-contracts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Consistent Node.js version
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Compile smart contracts
        run: npx hardhat compile

      - name: Run smart contract tests
        run: npx hardhat test
